pipeline {
    agent any

    environment {
        BROWSER = 'chrome'
    }

    stages {
        stage('My Repository') {
            steps {
                git 'https://github.com/princerana0702/End-to-end-automation-Sample-project-using-Python-for-testing-SauceDemo-Labs'

            }
        }

        stage('Setup Python Environment') {
            steps {
                sh 'pip install --upgrade pip'
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Selenium Tests') {
            steps {
                sh 'pytest tests/ --html=reports/test_report.html --self-contained-html'
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: 'reports/test_report.html', fingerprint: true
            }
        }
    }
}
